In [2]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
import cv2 as cv
from facenet.models.mtcnn import MTCNN
from utils.functions import extract_face

image = cv.imread("images/cmnd.jpg")

rgb_image = cv.cvtColor(image, cv.COLOR_BGR2RGB)

mtcnn = MTCNN()

face, box, _ = extract_face(rgb_image, mtcnn)

plt.imshow(face)


In [1]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

image = cv2.imread("images/cmnd.jpg")

gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
_,thresh = cv2.threshold(gray,128,255,cv2.THRESH_BINARY)
plt.imshow(thresh, 'gray')

thresh = cv2.bitwise_not(thresh)

element = cv2.getStructuringElement(shape=cv2.MORPH_RECT, ksize=(7, 7))

dilate = cv2.dilate(thresh,element,6)
plt.imshow(dilate, 'gray')
erode = cv2.erode(dilate,element,6)
plt.imshow(erode, 'gray')

morph_img = thresh.copy()
cv2.morphologyEx(src=erode, op=cv2.MORPH_CLOSE, kernel=element, dst=morph_img)
plt.imshow(morph_img, 'gray')
contours,_ = cv2.findContours(morph_img,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)

areas = [cv2.contourArea(c) for c in contours]

sorted_areas = np.sort(areas)
cnt=contours[areas.index(sorted_areas[-3])] #the third biggest contour is the face
r = cv2.boundingRect(cnt)
cv2.rectangle(image,(r[0],r[1]),(r[0]+r[2],r[1]+r[3]),(0,0,255),2)
plt.imshow(image)


In [13]:
import random
random.randint(1,5)

4

In [5]:
from face_verification import *
from verification_models import VGGFace2, VGGFace

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

detector_model = MTCNN(device = device)

image = cv.imread("images/template.jpg")

rgb_image = cv.cvtColor(image, cv.COLOR_BGR2RGB)

boxes, _, = detector_model.detect(rgb_image)

boxes

In [1]:
from face_verification import *
from verification_models import VGGFace2, VGGFace

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

detector_model = MTCNN(device = device)
face2 = VGGFace2.load_model(device = device)
face1 = VGGFace.load_model(device = device)

Weights loaded successfully from path: d:\eKYC\verification_models\weights/vggface2_weights.pt


In [2]:
filename1 = "images/trang2.jpg"
filename2 = "images/trang.jpg"

image1 = get_image(filename1)
image2 = get_image(filename2)


results = verify(image1, image2, detector_model, face1)
results2 = verify(image1, image2, detector_model, face2, model_name = 'VGG-Face2')

print(results)
print(results2)

tensor([580]) tensor([580])
tensor([466]) tensor([466])
tensor([True])
tensor([True])


In [3]:
filename1 = "images/thanh2.png"
filename2 = "images/thanh4.jpg"

image1 = get_image(filename1)
image2 = get_image(filename2)


results = verify(image1, image2, detector_model, face1)
results2 = verify(image1, image2, detector_model, face2, model_name = 'VGG-Face2')

print(results)
print(results2)

tensor([2414]) tensor([2414])
tensor([466]) tensor([466])
tensor([True])
tensor([True])


In [4]:
filename1 = "images/ngoc.jpg"
filename2 = "images/ngoc2.jpg"

image1 = get_image(filename1)
image2 = get_image(filename2)


results = verify(image1, image2, detector_model, face1)
results2 = verify(image1, image2, detector_model, face2, model_name = 'VGG-Face2')

print(results)
print(results2)

tensor([866]) tensor([866])
tensor([466]) tensor([466])
tensor([True])
tensor([True])


In [5]:
filename1 = "images/thanh.jpg"
filename2 = "images/ngoc2.jpg"

image1 = get_image(filename1)
image2 = get_image(filename2)


results = verify(image1, image2, detector_model, face1)
results2 = verify(image1, image2, detector_model, face2, model_name = 'VGG-Face2')

print(results)
print(results2)

tensor([571]) tensor([866])
tensor([466]) tensor([466])
tensor([False])
tensor([True])


In [2]:
a = '123'
b = 1
f"{b}, {a}"

'1, 123'